eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-consumer

logging:
  file: ${spring.application.name}.log